services:
  mongodb:
    image: mongo:latest
    volumes:
      - mongodb_data:/data/db
    restart: always

  citybikes:
    image: askhem/citybikes:latest
    environment:
      - MONGODB_URL=mongodb://mongodb:27017/
    depends_on:
      - mongodb
    restart: always

volumes:
  mongodb_data:
  