services:
  citybikes:
    build: .
    environment:
      - MONGODB_URL=mongodb://mongodb:27017/
    depends_on:
      - mongodb
    networks:
      - citybikes-network
    restart: unless-stopped

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - citybikes-network
    restart: unless-stopped

networks:
  citybikes-network:
    driver: bridge

volumes:
  mongodb_data: